dist: xenial
language: python
install:
  - pip install mkdocs==0.17.2
  - pip install mkdocs-material==2.5.2
  - pip install pymdown-extensions
  - pip install python-markdown-math
  - pip install git+https://github.com/szcf-weiya/mkdocs-git-revision-date-plugin.git
script:
  - python gentag.py
  - mkdocs build
  - mv rmds/_site/ site/rmds
    
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: site
  on:
    branch: master
